### ISSUE TITLE
Use the new infrastructure type taxonomy

### ISSUE THREAD

**Issue by dabreegster** [nptscot/editor#6]
and colours

**Comment by Robinlovelace** [comment]
Relevant code with agreed colours:

https://github.com/nptscot/osmactive/blob/b08d91b310187c6b344d3682e040e47ce2519be1/R/osmactive.R#L437-L446

Relevant website comment: https://github.com/nptscot/nptscot.github.io/issues/243#issuecomment-2419535793

**Comment by dabreegster** [comment]
Thank you! I'm assuming we're still modelling "mixed traffic" -- roads considered parts of a route but without anything else, except maybe traffic calming or being part of an LTN. And I'm still going to retain an "unknown" category, to indicate "some kind of provision here beyond mixed traffic, but not sure what yet"

**Comment by dabreegster** [comment]
![image](https://github.com/user-attachments/assets/a966703a-837f-4756-b386-d250dbca4203)
Done

**Comment by Robinlovelace** [comment]
Awesome
